name: blockchain_messenger
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  android_id: ^0.3.6
  appcheck: ^1.0.6
  device_info_plus: ^9.1.0
  external_path: ^1.0.3
  ffi: ^2.1.2
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_webrtc: ^0.9.42+hotfix.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^0.8.7+1
  intl: ^0.18.1
  path_provider: ^2.1.1
  provider: ^6.0.5
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  sqflite: ^2.3.0
  unique_identifier: ^0.3.0
  url_launcher: ^6.1.14
  uuid: ^3.0.7
  walletconnect_dart: ^0.0.11
  walletconnect_flutter_v2: ^2.1.5
  web3dart: ^2.7.1
  native_add:
    path: ./native_add




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/smartcontracts/user_contract.json
    - assets/logo.png
    - assets/profile.png
    - assets/complete.png
    - assets/test.jpg
    - assets/sign1.png
    - assets/sign2.png
    - assets/sign3.png
    - assets/sign4.png
    - assets/sign5.png
    - assets/daun.png
    - assets/yeri.png
    - assets/hyunjoo.png
    - assets/sslab.jpg
    - assets/generateAccount.png
    - assets/chat.png
    - assets/video.png
    - assets/audio.png
    

    
